# -*- coding: utf-8 -*-
"""Vizualitation data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pE7pQa8dC-z-hSKSdooAdF0nBrCINgac
"""

import pandas as pd
import matplotlib.pyplot as plt

!gdown --id 1ftzk0YxG48FlzBOkd6eNi3ANxFFZc8zC

data = pd.read_csv('Data Film Deadpool And Wolverine.csv')

print(data.head())

sentiment_counts = data['sentiment'].value_counts()

plt.figure(figsize=(8, 6))
plt.bar(sentiment_counts.index, sentiment_counts.values)
plt.title('Distribusi Sentiment')
plt.xlabel('Sentimen')
plt.ylabel('Jumlah')
plt.xticks(rotation=0)
plt.tight_layout()
plt.show()